spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/employee?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
    username: root
    password: LIZHONGJIE199608

  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    show-sql: false
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd

server:
  port: 9999
  tomcat:
    uri-encoding: utf-8

security:
  basic:
    enabled: false
  user:
    name: admin
    password: 123
